# ---- Build Stage ----
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
  
  # Copy pom first â†’ resolve deps faster
COPY pom.xml .
RUN mvn dependency:go-offline
  
  # Copy source code
COPY src ./src
RUN mvn clean package -DskipTests
  
  # ---- Run Stage ----
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar
  
  # Render gives PORT dynamically
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
